---
   - name : yum install
     yum:
         name: 'lvm*'
         state: present
   - name: vg_data volume group creation
     lvg:
          vg: vg_data 
          pvs: 
          - /dev/xvdh
   - name: db00 lvm creation
     lvol:
          vg: vg_data 
          lv: db00
          size: 500m

          path: /opt
          src : /dev/xvdh
          state: mounted
   - name: db01 lvm creation
     lvol:
          vg: vg_data 
          lv: db01
          size: 500m    
     ansible.posix.mount:
          path: /var/log  
          src : /dev/xvdh 
          state: mounted      
   - name: create file system for db00
     filesystem:
       fstype: ext4
       dev: /dev/vg_data/db00
   - name: create file system for db01
     filesystem:
       fstype: ext4
       dev: /dev/vg_data/db01
