---
# aws ec2 ansible dynamic inventory plugin
plugin: aws_ec2
aws_access_key_id : 
aws_secret_access_key : 
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region